/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0c0869b6b3bb1f594c3c3baf0882f8f0)
interface __BaseEnv_Env {
	ROOM: DurableObjectNamespace<import("./src/index").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
