/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c73de3ff64a5ee0a70f8a2f0dd4e3309)
interface __BaseEnv_Env {
	HOST_ROOM: DurableObjectNamespace<import("./src/index").HostRoom>;
	RATE_LIMIT: DurableObjectNamespace<import("./src/index").RateLimit>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "HostRoom" | "RateLimit";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
